// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

import API from './awa-api';



const awsConfig = {
        // 'aws_app_analytics': 'enable',
        "app_header": "360 Web",
        "Storage": {
                "bucket": 'hmsdev-userfiles-mobilehub-717810367', //REQUIRED -  Amazon S3 bucket
        },
        'aws_cloud_logic': 'enable',
        'aws_cloud_logic_custom': [{
                "id": "36jllv9kxa",
                "name": "HMS 360",
                "description": "",
                "endpoint": "https://36jllv9kxa.execute-api.us-east-1.amazonaws.com/dev",
                "region": "us-east-1",
                "paths": [
                        "/admin", "/admin/groups", "/admin/users", "/authenticate",
                        "/config", "/config/firebase", "/config/usercache", "/group",
                        "/posts", "/posts/add", "/posts/comments", "/posts/comments/add",
                        "/posts/edit", "/posts/like", "/posts/view", "/unlike", "/user",
                        "/user/add", "/user/me", "/user/me/updatepicture"
                ]
        }],
        'aws_cognito_identity_pool_id': 'us-east-1:d4e82f77-770d-4830-b3bc-b4dc0361f874',
        'aws_cognito_region': 'us-east-1',
        'aws_content_delivery': 'enable',
        'aws_content_delivery_bucket': 'hmsdev-hosting-mobilehub-717810367',
        'aws_content_delivery_bucket_region': 'us-east-1',
        'aws_content_delivery_cloudfront': 'enable',
        'aws_content_delivery_cloudfront_domain': 'd1tgtwzan4sxe5.cloudfront.net',
        // 'aws_mobile_analytics_app_id': '9bfa78abda5f4f3fb93889b4a8c86765',
        // 'aws_mobile_analytics_app_region': 'us-east-1',
        'aws_project_id': '42dc39d0-9d29-432b-8854-2eff045bdb2d',
        'aws_project_name': 'HMS DEV',
        'aws_project_region': 'us-east-1',
        'aws_resource_name_prefix': 'hmsdev-mobilehub-717810367',
        'aws_sign_in_enabled': 'enable',
        'aws_user_pools': 'enable',
        'aws_user_pools_id': 'us-east-1_OvuCD8YgW',
        'aws_user_pools_web_client_id': '5d9u6q7cbarafhf49rpc5uhopm',
        API
}



export default awsConfig;