/*
 *
 * ParentChildren constants
 *
 */

export const DEFAULT_ACTION = 'app/ParentChildren/DEFAULT_ACTION';
export const LOAD_PARENT_CHILDREN = 'LOAD_PARENT_CHILDREN';
export const LOAD_PARENT_CHILDREN_SUCCESS = 'LOAD_PARENT_CHILDREN_SUCCESS';
export const LOAD_PARENT_CHILDREN_ERROR = 'LOAD_PARENT_CHILDREN_ERROR';
